// <auto-generated />
namespace SeekARide.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class linkedtripInfotorequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(linkedtripInfotorequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201604252017130_linked tripInfo to request"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
