// <auto-generated />
namespace SeekARide.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangestoTrip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangestoTrip));
        
        string IMigrationMetadata.Id
        {
            get { return "201604152131007_Changes to Trip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
